name       : mupdf
version    : 1.18.0
release    : 7
source     :
    - https://mupdf.com/downloads/archive/mupdf-1.18.0-source.tar.xz : 592d4f6c0fba41bb954eb1a41616661b62b134d5b383e33bd45a081af5d4a59a
homepage   : https://mupdf.com
license    : AGPL-3.0-or-later
component  : office.viewers
summary    : lightweight PDF, XPS, and e-book viewer
description: |
    MuPDF is a lightweight PDF, XPS, and E-book viewer.
    MuPDF consists of a software library, command line tools, and viewers for various platforms.
    The renderer in MuPDF is tailored for high quality anti-aliased graphics. It renders text with metrics and spacing accurate to within fractions of a pixel for the highest fidelity in reproducing the look of a printed page on screen.
    The viewer is small, fast, yet complete. It supports many document formats, such as PDF, XPS, OpenXPS, CBZ, EPUB, and FictionBook 2. You can annotate PDF documents and fill out forms with the mobile viewers (this feature is coming soon to the desktop viewer as well).
    The command line tools allow you to annotate, edit, and convert documents to other formats such as HTML, SVG, PDF, and CBZ. You can also write scripts to manipulate documents using Javascript.
libsplit   : false
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(glu)
    - pkgconfig(gumbo)
    - pkgconfig(harfbuzz)
    - pkgconfig(jbig2dec)
    - pkgconfig(lcms2)
    - pkgconfig(libcurl)
    - pkgconfig(libopenjp2)
    - pkgconfig(libturbojpeg)
    - pkgconfig(mujs)
    - pkgconfig(xext)
    - pkgconfig(xi)
    - pkgconfig(xrandr)
setup      : |
    # MuPDF ships a patched freeglut that supports unicode. Use it.
    find thirdparty -mindepth 1 -maxdepth 1 -not -name freeglut -exec rm -rf {} +
    %patch -p1 < $pkgfiles/Link-against-shared-libs.patch
    echo "\
        USE_SYSTEM_FREETYPE=yes
        USE_SYSTEM_GUMBO=yes
        USE_SYSTEM_HARFBUZZ=yes
        USE_SYSTEM_JBIG2DEC=yes
        USE_SYSTEM_LCMS2=yes
        USE_SYSTEM_LIBJPEG=yes
        USE_SYSTEM_MUJS=yes
        USE_SYSTEM_OPENJPEG=yes
        USE_SYSTEM_ZLIB=yes" > user.make
build      : |
    %make
install    : |
    %make_install prefix=%PREFIX%
    install -Dm00644 docs/logo/mupdf-logo.svg $installdir/usr/share/icons/hicolor/scalable/apps/mupdf.svg
    install -Dm00644 $pkgfiles/mupdf.desktop -t $installdir/usr/share/applications

    # Not used anywhere.
    rm -rf $installdir/usr/lib/libmupdf-third.so
