name       : mupdf
version    : 1.16.1
release    : 1
source     :
    - https://mupdf.com/downloads/archive/mupdf-1.16.1-source.tar.xz : 6fe78184bd5208f9595e4d7f92bc8df50af30fbe8e2c1298b581c84945f2f5da
homepage   : https://mupdf.com/
license    : AGPL-3.0-or-later
component  : office.viewers
summary    : lightweight PDF, XPS, and E-book viewer
description: |
    MuPDF is a lightweight PDF, XPS, and E-book viewer.
    MuPDF consists of a software library, command line tools, and viewers for various platforms.
    The renderer in MuPDF is tailored for high quality anti-aliased graphics. It renders text with metrics and spacing accurate to within fractions of a pixel for the highest fidelity in reproducing the look of a printed page on screen.
    The viewer is small, fast, yet complete. It supports many document formats, such as PDF, XPS, OpenXPS, CBZ, EPUB, and FictionBook 2. You can annotate PDF documents and fill out forms with the mobile viewers (this feature is coming soon to the desktop viewer as well).
    The command line tools allow you to annotate, edit, and convert documents to other formats such as HTML, SVG, PDF, and CBZ. You can also write scripts to manipulate documents using Javascript.
libsplit   : false
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(freeglut)
    - pkgconfig(libjpeg)
    - pkgconfig(libopenjp2)
    - pkgconfig(libjpeg)
    - pkgconfig(lcms2)
    - pkgconfig(harfbuzz)
    - pkgconfig(libcurl)
    - pkgconfig(freetype2)
setup      : |
    %patch -p1 < $pkgfiles/0001-shared_libs-1.patch
build      : |
    %make USE_SYSTEM_LIBS=yes
install    : |
    %make_install prefix=/usr USE_SYSTEM_LIBS=yes
    install -Dm 00644 docs/logo/mupdf.png $installdir/usr/share/pixmaps/mupdf.png
    install -Dm 00644 $pkgfiles/mupdf.desktop $installdir/usr/share/applications/mupdf.desktop
